### ISSUE TITLE
Add button to bring all windows to foreground

### ISSUE THREAD

**Issue by davilimap** [slyjeff/ArkhamOverlay#24]
For the app, if you minimize a window or open another window over it, having to bring each window to the foreground is not ideal. A small button that does that on the main window might be nice.

This is very minor, and might not even be worth the effort, but would make debugging easier.

**Comment by slyjeff** [comment]
I think this is more than minor- the way it currently is feels very bad.

Ideally, activating any of the windows should bring all the others into view, rather than a button click. I quickly tried to accomplish this, but couldn't make it work.

I'm going to remove the "nice to have", bcause I think this actually is something we should get in sooner rather than later.
