### ISSUE TITLE
Add ability to show player hands

### ISSUE THREAD

**Issue by davilimap** [slyjeff/ArkhamOverlay#5]
Add the ability to show players' hands as well as to add and remove cards in each player's hand

**Comment by slyjeff** [comment]
I think the way that this would work is there would be an "Add  Card To Hand", so you click it, and then the next card you click is added to your hand instead of showing. We need some way of visually representing that state. Then of course "Remove Card From Hand" that works in the same way. Then another button to toggle the visibility of the hand, which I think sould be at the bottom of the screen rather than in the normal row.

This is what I've been brainstorming at least.

**Comment by slyjeff** [comment]
Another thing to consider is sometimes Encounter cards go into hands, so encounter cards will have to have options for adding to player hands. "Add to player 1 hand" and work the same way. You'd need four buttons. Only one remove though.

**Comment by slyjeff** [comment]
Ok, so update on this os a few things:

1. Rather than an "Add to hand" button, it will be a right clik on the cazrd to add/remove it from hand.
2. Hand display needs to be sized different from other cards, because we'll be displaying a lot of cards at once. I think the hand should appear at the bottom of the screen (think TTS), and should size based on the number of cards in hand vs the width of the screen.
3. There should be a version of hand dispaly (right click) that not only displays the hand, but also displays the investigator card, and health/sanity/resources.
